# Generated by Django 3.1.7 on 2022-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
